@startuml

package "Client side" as client {
  [Play Track]
  [Liked Tracks]
  [Auth]
}

folder "Backend" as backend{
    frame "Marshall library" as marshal{
           [generate_token_by_username_and_password()\nClient.from_token(token)] as back_auth
           [client.users_likes_tracks().tracks] as liked_tracks
           [lolol] as play_track
    }
}

database "Yandex API" as yandex{
    frame "DATA"{
        [DATAs]
    }
}

note left of back_auth
token will be generated, encrypted
and stored in some file, so that when
pc is restarted we would read this token
from file and enter to the accaunt
end note


[Auth] --> back_auth : endpoint: auth/main\n request:post\n body: login & passwrd\n 
[Liked Tracks] --> liked_tracks: endpoint: liked_tracks/\nrequest: get\n
liked_tracks --> yandex: request: get\n
back_auth --> yandex : request: post\n
yandex -[#blue]-> back_auth: response\n body: yandex_music.Client
yandex -[#blue]-> liked_tracks: response\n body: liked tracks
back_auth -[#blue]-> [Auth]: response\n body: yandex_music.Client
liked_tracks -[#blue]-> [Liked Tracks]: response\n body: liked tracks

[Play Track] --> [play_track]: endpoint: play/\n request: get\n body: trackId\n 

client -[hidden]-> backend
' backend -[hidden]-> yandex

@enduml